export const allDoctorsDummyData = [
  {
    id: 1,
    doctor_name: 'Cornell',
    doctor_image: 'http://dummyimage.com/174x100.png/cc0000/ffffff',
    doctor_gender: 'Female',
    doctor_department: 'Clothing',
    doctor_specialization: 'Clear Eyes Complete 7 Symptom Relief',
    doctor_degree: 'Operator',
    doctor_mobile: '+30-292-839-6679',
    doctor_email: 'cfatscher0@bbc.co.uk',
    doctor_joining_date: '11/8/2021',
  },
  {
    id: 2,
    doctor_name: 'Janice',
    doctor_image: 'http://dummyimage.com/148x100.png/dddddd/000000',
    doctor_gender: 'Female',
    doctor_department: 'Shoes',
    doctor_specialization: 'leader aspirin',
    doctor_degree: 'Product Engineer',
    doctor_mobile: '+86-914-470-4784',
    doctor_email: 'jkibble1@smugmug.com',
    doctor_joining_date: '1/15/2021',
  },
  {
    id: 3,
    doctor_name: 'Lane',
    doctor_image: 'http://dummyimage.com/160x100.png/ff4444/ffffff',
    doctor_gender: 'Female',
    doctor_department: 'Clothing',
    doctor_specialization: 'Carvedilol',
    doctor_degree: 'Physical Therapy Assistant',
    doctor_mobile: '+253-157-311-1176',
    doctor_email: 'lmatten2@bravesites.com',
    doctor_joining_date: '11/25/2020',
  },
  {
    id: 4,
    doctor_name: 'Dominique',
    doctor_image: 'http://dummyimage.com/127x100.png/dddddd/000000',
    doctor_gender: 'Male',
    doctor_department: 'Books',
    doctor_specialization: 'DOUBLE PERFECTION LUMIERE',
    doctor_degree: 'Senior Cost Accountant',
    doctor_mobile: '+62-535-654-6700',
    doctor_email: 'dbedo3@yellowbook.com',
    doctor_joining_date: '8/13/2021',
  },
  {
    id: 5,
    doctor_name: 'Findley',
    doctor_image: 'http://dummyimage.com/192x100.png/cc0000/ffffff',
    doctor_gender: 'Female',
    doctor_department: 'Jewelry',
    doctor_specialization: 'Doxazosin',
    doctor_degree: 'Research Nurse',
    doctor_mobile: '+963-202-928-8678',
    doctor_email: 'frudsdell4@cocolog-nifty.com',
    doctor_joining_date: '6/10/2021',
  },
  {
    id: 6,
    doctor_name: 'Frasquito',
    doctor_image: 'http://dummyimage.com/154x100.png/ff4444/ffffff',
    doctor_gender: 'Female',
    doctor_department: 'Games',
    doctor_specialization: 'Treatment Set TS345303',
    doctor_degree: 'Information Systems Manager',
    doctor_mobile: '+48-923-841-1235',
    doctor_email: 'fwhylie5@joomla.org',
    doctor_joining_date: '6/21/2021',
  },
  {
    id: 7,
    doctor_name: 'Flossy',
    doctor_image: 'http://dummyimage.com/224x100.png/cc0000/ffffff',
    doctor_gender: 'Male',
    doctor_department: 'Grocery',
    doctor_specialization: 'M-END',
    doctor_degree: 'Information Systems Manager',
    doctor_mobile: '+81-847-203-1422',
    doctor_email: 'flangworthy6@cbc.ca',
    doctor_joining_date: '12/19/2020',
  },
  {
    id: 8,
    doctor_name: 'Barbaraanne',
    doctor_image: 'http://dummyimage.com/121x100.png/dddddd/000000',
    doctor_gender: 'Female',
    doctor_department: 'Outdoors',
    doctor_specialization: 'Acetaminophen',
    doctor_degree: 'Database Administrator III',
    doctor_mobile: '+381-259-475-9155',
    doctor_email: 'bashurst7@buzzfeed.com',
    doctor_joining_date: '9/21/2021',
  },
  {
    id: 9,
    doctor_name: 'Whitney',
    doctor_image: 'http://dummyimage.com/163x100.png/dddddd/000000',
    doctor_gender: 'Male',
    doctor_department: 'Games',
    doctor_specialization: 'Toxodetox',
    doctor_degree: 'Research Assistant IV',
    doctor_mobile: '+63-136-557-3875',
    doctor_email: 'wraiment8@earthlink.net',
    doctor_joining_date: '5/11/2021',
  },
  {
    id: 10,
    doctor_name: 'Ephrem',
    doctor_image: 'http://dummyimage.com/219x100.png/cc0000/ffffff',
    doctor_gender: 'Male',
    doctor_department: 'Movies',
    doctor_specialization: 'Effient',
    doctor_degree: 'Safety Technician I',
    doctor_mobile: '+33-774-545-3818',
    doctor_email: 'ekimble9@nih.gov',
    doctor_joining_date: '3/1/2021',
  },
];
