export const allDoctorsDummyData = [
  {
    id: 1,
    name: 'Cornell',
    image: 'http://dummyimage.com/174x100.png/cc0000/ffffff',
    gender: 'Female',
    department: 'Clothing',
    specialization: 'Clear Eyes Complete 7 Symptom Relief',
    degree: 'Operator',
    mobile: '+30-292-839-6679',
    email: 'cfatscher0@bbc.co.uk',
    joining_date: '11/8/2021',
    // status: 'active',
    // BMDC_number: 39393,
    // experience: 6, // years
    // consultation_fee: 900,
    // current_address: 'Motijheel, Dhaka',
    // permanent_address: 'Motijheel, Dhaka',
    // birthday: '12-22-1993',
    // work_experience: [
    //   {
    //     medical_name: 'fakdf medical hospital',
    //     time: 'march 2017 - now',
    //     post: ' professor',
    //   },
    //   {
    //     medical_name: 'fakdf medical hospital',
    //     time: 'january 2012 - march 2017',
    //     post: 'assistant professor',
    //   },
    // ],
    // education: [
    //   {
    //     school_name: 'fakdfa medical school',
    //     time: 'march 2017 - now',
    //   },
    //   {
    //     school_name: 'fakdfa medical school',
    //     time: 'march 2017 - now',
    //   },
    // ],
  },
  {
    id: 2,
    name: 'Janice',
    image: 'http://dummyimage.com/148x100.png/dddddd/000000',
    gender: 'Female',
    department: 'Shoes',
    specialization: 'leader aspirin',
    degree: 'Product Engineer',
    mobile: '+86-914-470-4784',
    email: 'jkibble1@smugmug.com',
    joining_date: '1/15/2021',
  },
  {
    id: 3,
    name: 'Lane',
    image: 'http://dummyimage.com/160x100.png/ff4444/ffffff',
    gender: 'Female',
    department: 'Clothing',
    specialization: 'Carvedilol',
    degree: 'Physical Therapy Assistant',
    mobile: '+253-157-311-1176',
    email: 'lmatten2@bravesites.com',
    joining_date: '11/25/2020',
  },
  {
    id: 4,
    name: 'Dominique',
    image: 'http://dummyimage.com/127x100.png/dddddd/000000',
    gender: 'Male',
    department: 'Books',
    specialization: 'DOUBLE PERFECTION LUMIERE',
    degree: 'Senior Cost Accountant',
    mobile: '+62-535-654-6700',
    email: 'dbedo3@yellowbook.com',
    joining_date: '8/13/2021',
  },
  {
    id: 5,
    name: 'Findley',
    image: 'http://dummyimage.com/192x100.png/cc0000/ffffff',
    gender: 'Female',
    department: 'Jewelry',
    specialization: 'Doxazosin',
    degree: 'Research Nurse',
    mobile: '+963-202-928-8678',
    email: 'frudsdell4@cocolog-nifty.com',
    joining_date: '6/10/2021',
  },
  {
    id: 6,
    name: 'Frasquito',
    image: 'http://dummyimage.com/154x100.png/ff4444/ffffff',
    gender: 'Female',
    department: 'Games',
    specialization: 'Treatment Set TS345303',
    degree: 'Information Systems Manager',
    mobile: '+48-923-841-1235',
    email: 'fwhylie5@joomla.org',
    joining_date: '6/21/2021',
  },
  {
    id: 7,
    name: 'Flossy',
    image: 'http://dummyimage.com/224x100.png/cc0000/ffffff',
    gender: 'Male',
    department: 'Grocery',
    specialization: 'M-END',
    degree: 'Information Systems Manager',
    mobile: '+81-847-203-1422',
    email: 'flangworthy6@cbc.ca',
    joining_date: '12/19/2020',
  },
  {
    id: 8,
    name: 'Barbaraanne',
    image: 'http://dummyimage.com/121x100.png/dddddd/000000',
    gender: 'Female',
    department: 'Outdoors',
    specialization: 'Acetaminophen',
    degree: 'Database Administrator III',
    mobile: '+381-259-475-9155',
    email: 'bashurst7@buzzfeed.com',
    joining_date: '9/21/2021',
  },
  {
    id: 9,
    name: 'Whitney',
    image: 'http://dummyimage.com/163x100.png/dddddd/000000',
    gender: 'Male',
    department: 'Games',
    specialization: 'Toxodetox',
    degree: 'Research Assistant IV',
    mobile: '+63-136-557-3875',
    email: 'wraiment8@earthlink.net',
    joining_date: '5/11/2021',
  },
  {
    id: 10,
    name: 'Ephrem',
    image: 'http://dummyimage.com/219x100.png/cc0000/ffffff',
    gender: 'Male',
    department: 'Movies',
    specialization: 'Effient',
    degree: 'Safety Technician I',
    mobile: '+33-774-545-3818',
    email: 'ekimble9@nih.gov',
    joining_date: '3/1/2021',
  },
];
