import { IConsultant } from 'components/common/Consultant';

export const availableConsultants = (): IConsultant[] => {
  return [
    {
      id: 1,
      name: 'harry',
      isOnline: true,
      profilePic: '',
      bio: '',
      special: ['eye'],
      consultationFee: 200,
      followUpFee: 100,
      degrees: ['MBBS', 'FCPS'],
      rating: 5,
      conversations: '',
      communication: [],
    },
    {
      id: 2,
      name: 'harry',
      isOnline: true,
      profilePic: '',
      bio: '',
      special: ['eye'],
      consultationFee: 200,
      followUpFee: 100,
      degrees: ['MBBS', 'FCPS'],
      rating: 5,
      conversations: '',
      communication: [],
    },
    {
      id: 3,
      name: 'harry',
      isOnline: true,
      profilePic: '',
      bio: '',
      special: ['eye'],
      consultationFee: 200,
      followUpFee: 100,
      degrees: ['MBBS', 'FCPS'],
      rating: 5,
      conversations: '',
      communication: [],
    },
    {
      id: 4,
      name: 'harry',
      isOnline: true,
      profilePic: '',
      bio: '',
      special: ['eye'],
      consultationFee: 200,
      followUpFee: 100,
      degrees: ['MBBS', 'FCPS'],
      rating: 5,
      conversations: '',
      communication: [],
    },
  ];
};
